import { TokenType } from 'chevrotain';
export { TokenType };
export declare const AdditionOperator: TokenType;
export declare const Plus: TokenType;
export declare const Minus: TokenType;
export declare const MultiplicationOperator: TokenType;
export declare const Multi: TokenType;
export declare const Div: TokenType;
export declare const Factorial: TokenType;
export declare const Pi: TokenType;
export declare const SuperScriptNumber: TokenType;
export declare const SquareRoot: TokenType;
export declare const Percent: TokenType;
export declare const LParen: TokenType;
export declare const RParen: TokenType;
export declare const NumberLiteral: TokenType;
export declare const DecimalPlace: TokenType;
export declare const PowerFunc: TokenType;
export declare const LogFunc: TokenType;
export declare const Comma: TokenType;
export declare const WhiteSpace: TokenType;
export declare const allTokens: TokenType[];
export default allTokens;
